// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaymentOrderUpdate is the builder for updating PaymentOrder entities.
type PaymentOrderUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdate) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentOrderUpdate) SetUpdatedAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *PaymentOrderUpdate) SetOrderNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableOrderNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentOrderUpdate) SetUserID(v int64) *PaymentOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableUserID(v *int64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PaymentOrderUpdate) SetProvider(v string) *PaymentOrderUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableProvider(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetChannel sets the "channel" field.
func (_u *PaymentOrderUpdate) SetChannel(v string) *PaymentOrderUpdate {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableChannel(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// ClearChannel clears the value of the "channel" field.
func (_u *PaymentOrderUpdate) ClearChannel() *PaymentOrderUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentOrderUpdate) SetCurrency(v string) *PaymentOrderUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableCurrency(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentOrderUpdate) SetAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAmount(v *float64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentOrderUpdate) AddAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdate) SetStatus(v string) *PaymentOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableStatus(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProviderOrderID sets the "provider_order_id" field.
func (_u *PaymentOrderUpdate) SetProviderOrderID(v string) *PaymentOrderUpdate {
	_u.mutation.SetProviderOrderID(v)
	return _u
}

// SetNillableProviderOrderID sets the "provider_order_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableProviderOrderID(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetProviderOrderID(*v)
	}
	return _u
}

// ClearProviderOrderID clears the value of the "provider_order_id" field.
func (_u *PaymentOrderUpdate) ClearProviderOrderID() *PaymentOrderUpdate {
	_u.mutation.ClearProviderOrderID()
	return _u
}

// SetProviderPaymentID sets the "provider_payment_id" field.
func (_u *PaymentOrderUpdate) SetProviderPaymentID(v string) *PaymentOrderUpdate {
	_u.mutation.SetProviderPaymentID(v)
	return _u
}

// SetNillableProviderPaymentID sets the "provider_payment_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableProviderPaymentID(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetProviderPaymentID(*v)
	}
	return _u
}

// ClearProviderPaymentID clears the value of the "provider_payment_id" field.
func (_u *PaymentOrderUpdate) ClearProviderPaymentID() *PaymentOrderUpdate {
	_u.mutation.ClearProviderPaymentID()
	return _u
}

// SetProviderCheckoutID sets the "provider_checkout_id" field.
func (_u *PaymentOrderUpdate) SetProviderCheckoutID(v string) *PaymentOrderUpdate {
	_u.mutation.SetProviderCheckoutID(v)
	return _u
}

// SetNillableProviderCheckoutID sets the "provider_checkout_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableProviderCheckoutID(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetProviderCheckoutID(*v)
	}
	return _u
}

// ClearProviderCheckoutID clears the value of the "provider_checkout_id" field.
func (_u *PaymentOrderUpdate) ClearProviderCheckoutID() *PaymentOrderUpdate {
	_u.mutation.ClearProviderCheckoutID()
	return _u
}

// SetProviderPayload sets the "provider_payload" field.
func (_u *PaymentOrderUpdate) SetProviderPayload(v map[string]interface{}) *PaymentOrderUpdate {
	_u.mutation.SetProviderPayload(v)
	return _u
}

// ClearProviderPayload clears the value of the "provider_payload" field.
func (_u *PaymentOrderUpdate) ClearProviderPayload() *PaymentOrderUpdate {
	_u.mutation.ClearProviderPayload()
	return _u
}

// SetDescription sets the "description" field.
func (_u *PaymentOrderUpdate) SetDescription(v string) *PaymentOrderUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableDescription(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PaymentOrderUpdate) ClearDescription() *PaymentOrderUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdate) SetPaidAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdate) ClearPaidAt() *PaymentOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *PaymentOrderUpdate) SetExpiresAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableExpiresAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *PaymentOrderUpdate) ClearExpiresAt() *PaymentOrderUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentOrderUpdate) SetUser(v *User) *PaymentOrderUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdate) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentOrderUpdate) ClearUser() *PaymentOrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := paymentorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := paymentorder.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Channel(); ok {
		if err := paymentorder.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.channel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderOrderID(); ok {
		if err := paymentorder.ProviderOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_order_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider_order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderPaymentID(); ok {
		if err := paymentorder.ProviderPaymentIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_payment_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider_payment_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderCheckoutID(); ok {
		if err := paymentorder.ProviderCheckoutIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_checkout_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider_checkout_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	return nil
}

func (_u *PaymentOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(paymentorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(paymentorder.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(paymentorder.FieldChannel, field.TypeString, value)
	}
	if _u.mutation.ChannelCleared() {
		_spec.ClearField(paymentorder.FieldChannel, field.TypeString)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderOrderID(); ok {
		_spec.SetField(paymentorder.FieldProviderOrderID, field.TypeString, value)
	}
	if _u.mutation.ProviderOrderIDCleared() {
		_spec.ClearField(paymentorder.FieldProviderOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderPaymentID(); ok {
		_spec.SetField(paymentorder.FieldProviderPaymentID, field.TypeString, value)
	}
	if _u.mutation.ProviderPaymentIDCleared() {
		_spec.ClearField(paymentorder.FieldProviderPaymentID, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderCheckoutID(); ok {
		_spec.SetField(paymentorder.FieldProviderCheckoutID, field.TypeString, value)
	}
	if _u.mutation.ProviderCheckoutIDCleared() {
		_spec.ClearField(paymentorder.FieldProviderCheckoutID, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderPayload(); ok {
		_spec.SetField(paymentorder.FieldProviderPayload, field.TypeJSON, value)
	}
	if _u.mutation.ProviderPayloadCleared() {
		_spec.ClearField(paymentorder.FieldProviderPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(paymentorder.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(paymentorder.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(paymentorder.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(paymentorder.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentOrderUpdateOne is the builder for updating a single PaymentOrder entity.
type PaymentOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentOrderUpdateOne) SetUpdatedAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *PaymentOrderUpdateOne) SetOrderNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableOrderNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentOrderUpdateOne) SetUserID(v int64) *PaymentOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableUserID(v *int64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PaymentOrderUpdateOne) SetProvider(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableProvider(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetChannel sets the "channel" field.
func (_u *PaymentOrderUpdateOne) SetChannel(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableChannel(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// ClearChannel clears the value of the "channel" field.
func (_u *PaymentOrderUpdateOne) ClearChannel() *PaymentOrderUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentOrderUpdateOne) SetCurrency(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableCurrency(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentOrderUpdateOne) SetAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAmount(v *float64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentOrderUpdateOne) AddAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdateOne) SetStatus(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableStatus(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProviderOrderID sets the "provider_order_id" field.
func (_u *PaymentOrderUpdateOne) SetProviderOrderID(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetProviderOrderID(v)
	return _u
}

// SetNillableProviderOrderID sets the "provider_order_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableProviderOrderID(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetProviderOrderID(*v)
	}
	return _u
}

// ClearProviderOrderID clears the value of the "provider_order_id" field.
func (_u *PaymentOrderUpdateOne) ClearProviderOrderID() *PaymentOrderUpdateOne {
	_u.mutation.ClearProviderOrderID()
	return _u
}

// SetProviderPaymentID sets the "provider_payment_id" field.
func (_u *PaymentOrderUpdateOne) SetProviderPaymentID(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetProviderPaymentID(v)
	return _u
}

// SetNillableProviderPaymentID sets the "provider_payment_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableProviderPaymentID(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetProviderPaymentID(*v)
	}
	return _u
}

// ClearProviderPaymentID clears the value of the "provider_payment_id" field.
func (_u *PaymentOrderUpdateOne) ClearProviderPaymentID() *PaymentOrderUpdateOne {
	_u.mutation.ClearProviderPaymentID()
	return _u
}

// SetProviderCheckoutID sets the "provider_checkout_id" field.
func (_u *PaymentOrderUpdateOne) SetProviderCheckoutID(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetProviderCheckoutID(v)
	return _u
}

// SetNillableProviderCheckoutID sets the "provider_checkout_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableProviderCheckoutID(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetProviderCheckoutID(*v)
	}
	return _u
}

// ClearProviderCheckoutID clears the value of the "provider_checkout_id" field.
func (_u *PaymentOrderUpdateOne) ClearProviderCheckoutID() *PaymentOrderUpdateOne {
	_u.mutation.ClearProviderCheckoutID()
	return _u
}

// SetProviderPayload sets the "provider_payload" field.
func (_u *PaymentOrderUpdateOne) SetProviderPayload(v map[string]interface{}) *PaymentOrderUpdateOne {
	_u.mutation.SetProviderPayload(v)
	return _u
}

// ClearProviderPayload clears the value of the "provider_payload" field.
func (_u *PaymentOrderUpdateOne) ClearProviderPayload() *PaymentOrderUpdateOne {
	_u.mutation.ClearProviderPayload()
	return _u
}

// SetDescription sets the "description" field.
func (_u *PaymentOrderUpdateOne) SetDescription(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableDescription(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PaymentOrderUpdateOne) ClearDescription() *PaymentOrderUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdateOne) SetPaidAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdateOne) ClearPaidAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *PaymentOrderUpdateOne) SetExpiresAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableExpiresAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *PaymentOrderUpdateOne) ClearExpiresAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentOrderUpdateOne) SetUser(v *User) *PaymentOrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdateOne) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentOrderUpdateOne) ClearUser() *PaymentOrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdateOne) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentOrderUpdateOne) Select(field string, fields ...string) *PaymentOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentOrder entity.
func (_u *PaymentOrderUpdateOne) Save(ctx context.Context) (*PaymentOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) SaveX(ctx context.Context) *PaymentOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := paymentorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := paymentorder.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Channel(); ok {
		if err := paymentorder.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.channel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderOrderID(); ok {
		if err := paymentorder.ProviderOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_order_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider_order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderPaymentID(); ok {
		if err := paymentorder.ProviderPaymentIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_payment_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider_payment_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderCheckoutID(); ok {
		if err := paymentorder.ProviderCheckoutIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_checkout_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider_checkout_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	return nil
}

func (_u *PaymentOrderUpdateOne) sqlSave(ctx context.Context) (_node *PaymentOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentorder.FieldID)
		for _, f := range fields {
			if !paymentorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(paymentorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(paymentorder.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(paymentorder.FieldChannel, field.TypeString, value)
	}
	if _u.mutation.ChannelCleared() {
		_spec.ClearField(paymentorder.FieldChannel, field.TypeString)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderOrderID(); ok {
		_spec.SetField(paymentorder.FieldProviderOrderID, field.TypeString, value)
	}
	if _u.mutation.ProviderOrderIDCleared() {
		_spec.ClearField(paymentorder.FieldProviderOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderPaymentID(); ok {
		_spec.SetField(paymentorder.FieldProviderPaymentID, field.TypeString, value)
	}
	if _u.mutation.ProviderPaymentIDCleared() {
		_spec.ClearField(paymentorder.FieldProviderPaymentID, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderCheckoutID(); ok {
		_spec.SetField(paymentorder.FieldProviderCheckoutID, field.TypeString, value)
	}
	if _u.mutation.ProviderCheckoutIDCleared() {
		_spec.ClearField(paymentorder.FieldProviderCheckoutID, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderPayload(); ok {
		_spec.SetField(paymentorder.FieldProviderPayload, field.TypeJSON, value)
	}
	if _u.mutation.ProviderPayloadCleared() {
		_spec.ClearField(paymentorder.FieldProviderPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(paymentorder.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(paymentorder.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(paymentorder.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(paymentorder.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
