// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaymentOrderCreate is the builder for creating a PaymentOrder entity.
type PaymentOrderCreate struct {
	config
	mutation *PaymentOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentOrderCreate) SetCreatedAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableCreatedAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentOrderCreate) SetUpdatedAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableUpdatedAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrderNo sets the "order_no" field.
func (_c *PaymentOrderCreate) SetOrderNo(v string) *PaymentOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PaymentOrderCreate) SetUserID(v int64) *PaymentOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *PaymentOrderCreate) SetProvider(v string) *PaymentOrderCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetChannel sets the "channel" field.
func (_c *PaymentOrderCreate) SetChannel(v string) *PaymentOrderCreate {
	_c.mutation.SetChannel(v)
	return _c
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableChannel(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetChannel(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *PaymentOrderCreate) SetCurrency(v string) *PaymentOrderCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableCurrency(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *PaymentOrderCreate) SetAmount(v float64) *PaymentOrderCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableAmount(v *float64) *PaymentOrderCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentOrderCreate) SetStatus(v string) *PaymentOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableStatus(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProviderOrderID sets the "provider_order_id" field.
func (_c *PaymentOrderCreate) SetProviderOrderID(v string) *PaymentOrderCreate {
	_c.mutation.SetProviderOrderID(v)
	return _c
}

// SetNillableProviderOrderID sets the "provider_order_id" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableProviderOrderID(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetProviderOrderID(*v)
	}
	return _c
}

// SetProviderPaymentID sets the "provider_payment_id" field.
func (_c *PaymentOrderCreate) SetProviderPaymentID(v string) *PaymentOrderCreate {
	_c.mutation.SetProviderPaymentID(v)
	return _c
}

// SetNillableProviderPaymentID sets the "provider_payment_id" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableProviderPaymentID(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetProviderPaymentID(*v)
	}
	return _c
}

// SetProviderCheckoutID sets the "provider_checkout_id" field.
func (_c *PaymentOrderCreate) SetProviderCheckoutID(v string) *PaymentOrderCreate {
	_c.mutation.SetProviderCheckoutID(v)
	return _c
}

// SetNillableProviderCheckoutID sets the "provider_checkout_id" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableProviderCheckoutID(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetProviderCheckoutID(*v)
	}
	return _c
}

// SetProviderPayload sets the "provider_payload" field.
func (_c *PaymentOrderCreate) SetProviderPayload(v map[string]interface{}) *PaymentOrderCreate {
	_c.mutation.SetProviderPayload(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PaymentOrderCreate) SetDescription(v string) *PaymentOrderCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableDescription(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *PaymentOrderCreate) SetPaidAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillablePaidAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *PaymentOrderCreate) SetExpiresAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableExpiresAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PaymentOrderCreate) SetUser(v *User) *PaymentOrderCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_c *PaymentOrderCreate) Mutation() *PaymentOrderMutation {
	return _c.mutation
}

// Save creates the PaymentOrder in the database.
func (_c *PaymentOrderCreate) Save(ctx context.Context) (*PaymentOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentOrderCreate) SaveX(ctx context.Context) *PaymentOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentOrderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paymentorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := paymentorder.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := paymentorder.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentOrderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentOrder.updated_at"`)}
	}
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "PaymentOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := paymentorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PaymentOrder.user_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "PaymentOrder.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := paymentorder.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Channel(); ok {
		if err := paymentorder.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.channel": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "PaymentOrder.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := paymentorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "PaymentOrder.amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProviderOrderID(); ok {
		if err := paymentorder.ProviderOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_order_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider_order_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProviderPaymentID(); ok {
		if err := paymentorder.ProviderPaymentIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_payment_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider_payment_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProviderCheckoutID(); ok {
		if err := paymentorder.ProviderCheckoutIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_checkout_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider_checkout_id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PaymentOrder.user"`)}
	}
	return nil
}

func (_c *PaymentOrderCreate) sqlSave(ctx context.Context) (*PaymentOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentOrderCreate) createSpec() (*PaymentOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentorder.Table, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(paymentorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(paymentorder.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Channel(); ok {
		_spec.SetField(paymentorder.FieldChannel, field.TypeString, value)
		_node.Channel = &value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(paymentorder.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProviderOrderID(); ok {
		_spec.SetField(paymentorder.FieldProviderOrderID, field.TypeString, value)
		_node.ProviderOrderID = &value
	}
	if value, ok := _c.mutation.ProviderPaymentID(); ok {
		_spec.SetField(paymentorder.FieldProviderPaymentID, field.TypeString, value)
		_node.ProviderPaymentID = &value
	}
	if value, ok := _c.mutation.ProviderCheckoutID(); ok {
		_spec.SetField(paymentorder.FieldProviderCheckoutID, field.TypeString, value)
		_node.ProviderCheckoutID = &value
	}
	if value, ok := _c.mutation.ProviderPayload(); ok {
		_spec.SetField(paymentorder.FieldProviderPayload, field.TypeJSON, value)
		_node.ProviderPayload = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(paymentorder.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(paymentorder.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentOrderCreate) OnConflict(opts ...sql.ConflictOption) *PaymentOrderUpsertOne {
	_c.conflict = opts
	return &PaymentOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentOrderCreate) OnConflictColumns(columns ...string) *PaymentOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderUpsertOne{
		create: _c,
	}
}

type (
	// PaymentOrderUpsertOne is the builder for "upsert"-ing
	//  one PaymentOrder node.
	PaymentOrderUpsertOne struct {
		create *PaymentOrderCreate
	}

	// PaymentOrderUpsert is the "OnConflict" setter.
	PaymentOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderUpsert) SetUpdatedAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateUpdatedAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldUpdatedAt)
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *PaymentOrderUpsert) SetOrderNo(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateOrderNo() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldOrderNo)
	return u
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsert) SetUserID(v int64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateUserID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldUserID)
	return u
}

// SetProvider sets the "provider" field.
func (u *PaymentOrderUpsert) SetProvider(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateProvider() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldProvider)
	return u
}

// SetChannel sets the "channel" field.
func (u *PaymentOrderUpsert) SetChannel(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldChannel, v)
	return u
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateChannel() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldChannel)
	return u
}

// ClearChannel clears the value of the "channel" field.
func (u *PaymentOrderUpsert) ClearChannel() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldChannel)
	return u
}

// SetCurrency sets the "currency" field.
func (u *PaymentOrderUpsert) SetCurrency(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateCurrency() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldCurrency)
	return u
}

// SetAmount sets the "amount" field.
func (u *PaymentOrderUpsert) SetAmount(v float64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateAmount() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *PaymentOrderUpsert) AddAmount(v float64) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsert) SetStatus(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateStatus() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldStatus)
	return u
}

// SetProviderOrderID sets the "provider_order_id" field.
func (u *PaymentOrderUpsert) SetProviderOrderID(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldProviderOrderID, v)
	return u
}

// UpdateProviderOrderID sets the "provider_order_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateProviderOrderID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldProviderOrderID)
	return u
}

// ClearProviderOrderID clears the value of the "provider_order_id" field.
func (u *PaymentOrderUpsert) ClearProviderOrderID() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldProviderOrderID)
	return u
}

// SetProviderPaymentID sets the "provider_payment_id" field.
func (u *PaymentOrderUpsert) SetProviderPaymentID(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldProviderPaymentID, v)
	return u
}

// UpdateProviderPaymentID sets the "provider_payment_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateProviderPaymentID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldProviderPaymentID)
	return u
}

// ClearProviderPaymentID clears the value of the "provider_payment_id" field.
func (u *PaymentOrderUpsert) ClearProviderPaymentID() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldProviderPaymentID)
	return u
}

// SetProviderCheckoutID sets the "provider_checkout_id" field.
func (u *PaymentOrderUpsert) SetProviderCheckoutID(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldProviderCheckoutID, v)
	return u
}

// UpdateProviderCheckoutID sets the "provider_checkout_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateProviderCheckoutID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldProviderCheckoutID)
	return u
}

// ClearProviderCheckoutID clears the value of the "provider_checkout_id" field.
func (u *PaymentOrderUpsert) ClearProviderCheckoutID() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldProviderCheckoutID)
	return u
}

// SetProviderPayload sets the "provider_payload" field.
func (u *PaymentOrderUpsert) SetProviderPayload(v map[string]interface{}) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldProviderPayload, v)
	return u
}

// UpdateProviderPayload sets the "provider_payload" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateProviderPayload() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldProviderPayload)
	return u
}

// ClearProviderPayload clears the value of the "provider_payload" field.
func (u *PaymentOrderUpsert) ClearProviderPayload() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldProviderPayload)
	return u
}

// SetDescription sets the "description" field.
func (u *PaymentOrderUpsert) SetDescription(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateDescription() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *PaymentOrderUpsert) ClearDescription() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldDescription)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentOrderUpsert) SetPaidAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdatePaidAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentOrderUpsert) ClearPaidAt() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldPaidAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *PaymentOrderUpsert) SetExpiresAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateExpiresAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *PaymentOrderUpsert) ClearExpiresAt() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentOrderUpsertOne) UpdateNewValues() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentOrderUpsertOne) Ignore() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderUpsertOne) DoNothing() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderCreate.OnConflict
// documentation for more info.
func (u *PaymentOrderUpsertOne) Update(set func(*PaymentOrderUpsert)) *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderUpsertOne) SetUpdatedAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateUpdatedAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *PaymentOrderUpsertOne) SetOrderNo(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateOrderNo() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsertOne) SetUserID(v int64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateUserID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetProvider sets the "provider" field.
func (u *PaymentOrderUpsertOne) SetProvider(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateProvider() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProvider()
	})
}

// SetChannel sets the "channel" field.
func (u *PaymentOrderUpsertOne) SetChannel(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateChannel() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateChannel()
	})
}

// ClearChannel clears the value of the "channel" field.
func (u *PaymentOrderUpsertOne) ClearChannel() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearChannel()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentOrderUpsertOne) SetCurrency(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateCurrency() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetAmount sets the "amount" field.
func (u *PaymentOrderUpsertOne) SetAmount(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *PaymentOrderUpsertOne) AddAmount(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateAmount() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsertOne) SetStatus(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateStatus() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetProviderOrderID sets the "provider_order_id" field.
func (u *PaymentOrderUpsertOne) SetProviderOrderID(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProviderOrderID(v)
	})
}

// UpdateProviderOrderID sets the "provider_order_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateProviderOrderID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProviderOrderID()
	})
}

// ClearProviderOrderID clears the value of the "provider_order_id" field.
func (u *PaymentOrderUpsertOne) ClearProviderOrderID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProviderOrderID()
	})
}

// SetProviderPaymentID sets the "provider_payment_id" field.
func (u *PaymentOrderUpsertOne) SetProviderPaymentID(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProviderPaymentID(v)
	})
}

// UpdateProviderPaymentID sets the "provider_payment_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateProviderPaymentID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProviderPaymentID()
	})
}

// ClearProviderPaymentID clears the value of the "provider_payment_id" field.
func (u *PaymentOrderUpsertOne) ClearProviderPaymentID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProviderPaymentID()
	})
}

// SetProviderCheckoutID sets the "provider_checkout_id" field.
func (u *PaymentOrderUpsertOne) SetProviderCheckoutID(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProviderCheckoutID(v)
	})
}

// UpdateProviderCheckoutID sets the "provider_checkout_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateProviderCheckoutID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProviderCheckoutID()
	})
}

// ClearProviderCheckoutID clears the value of the "provider_checkout_id" field.
func (u *PaymentOrderUpsertOne) ClearProviderCheckoutID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProviderCheckoutID()
	})
}

// SetProviderPayload sets the "provider_payload" field.
func (u *PaymentOrderUpsertOne) SetProviderPayload(v map[string]interface{}) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProviderPayload(v)
	})
}

// UpdateProviderPayload sets the "provider_payload" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateProviderPayload() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProviderPayload()
	})
}

// ClearProviderPayload clears the value of the "provider_payload" field.
func (u *PaymentOrderUpsertOne) ClearProviderPayload() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProviderPayload()
	})
}

// SetDescription sets the "description" field.
func (u *PaymentOrderUpsertOne) SetDescription(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateDescription() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PaymentOrderUpsertOne) ClearDescription() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearDescription()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentOrderUpsertOne) SetPaidAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdatePaidAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentOrderUpsertOne) ClearPaidAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *PaymentOrderUpsertOne) SetExpiresAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateExpiresAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *PaymentOrderUpsertOne) ClearExpiresAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *PaymentOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentOrderCreateBulk is the builder for creating many PaymentOrder entities in bulk.
type PaymentOrderCreateBulk struct {
	config
	err      error
	builders []*PaymentOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentOrder entities in the database.
func (_c *PaymentOrderCreateBulk) Save(ctx context.Context) ([]*PaymentOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentOrderCreateBulk) SaveX(ctx context.Context) []*PaymentOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentOrderUpsertBulk {
	_c.conflict = opts
	return &PaymentOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentOrderCreateBulk) OnConflictColumns(columns ...string) *PaymentOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderUpsertBulk{
		create: _c,
	}
}

// PaymentOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentOrder nodes.
type PaymentOrderUpsertBulk struct {
	create *PaymentOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentOrderUpsertBulk) UpdateNewValues() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentOrderUpsertBulk) Ignore() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderUpsertBulk) DoNothing() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentOrderUpsertBulk) Update(set func(*PaymentOrderUpsert)) *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderUpsertBulk) SetUpdatedAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateUpdatedAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *PaymentOrderUpsertBulk) SetOrderNo(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateOrderNo() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsertBulk) SetUserID(v int64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateUserID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetProvider sets the "provider" field.
func (u *PaymentOrderUpsertBulk) SetProvider(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateProvider() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProvider()
	})
}

// SetChannel sets the "channel" field.
func (u *PaymentOrderUpsertBulk) SetChannel(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateChannel() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateChannel()
	})
}

// ClearChannel clears the value of the "channel" field.
func (u *PaymentOrderUpsertBulk) ClearChannel() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearChannel()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentOrderUpsertBulk) SetCurrency(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateCurrency() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetAmount sets the "amount" field.
func (u *PaymentOrderUpsertBulk) SetAmount(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *PaymentOrderUpsertBulk) AddAmount(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateAmount() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsertBulk) SetStatus(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateStatus() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetProviderOrderID sets the "provider_order_id" field.
func (u *PaymentOrderUpsertBulk) SetProviderOrderID(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProviderOrderID(v)
	})
}

// UpdateProviderOrderID sets the "provider_order_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateProviderOrderID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProviderOrderID()
	})
}

// ClearProviderOrderID clears the value of the "provider_order_id" field.
func (u *PaymentOrderUpsertBulk) ClearProviderOrderID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProviderOrderID()
	})
}

// SetProviderPaymentID sets the "provider_payment_id" field.
func (u *PaymentOrderUpsertBulk) SetProviderPaymentID(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProviderPaymentID(v)
	})
}

// UpdateProviderPaymentID sets the "provider_payment_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateProviderPaymentID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProviderPaymentID()
	})
}

// ClearProviderPaymentID clears the value of the "provider_payment_id" field.
func (u *PaymentOrderUpsertBulk) ClearProviderPaymentID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProviderPaymentID()
	})
}

// SetProviderCheckoutID sets the "provider_checkout_id" field.
func (u *PaymentOrderUpsertBulk) SetProviderCheckoutID(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProviderCheckoutID(v)
	})
}

// UpdateProviderCheckoutID sets the "provider_checkout_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateProviderCheckoutID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProviderCheckoutID()
	})
}

// ClearProviderCheckoutID clears the value of the "provider_checkout_id" field.
func (u *PaymentOrderUpsertBulk) ClearProviderCheckoutID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProviderCheckoutID()
	})
}

// SetProviderPayload sets the "provider_payload" field.
func (u *PaymentOrderUpsertBulk) SetProviderPayload(v map[string]interface{}) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProviderPayload(v)
	})
}

// UpdateProviderPayload sets the "provider_payload" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateProviderPayload() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProviderPayload()
	})
}

// ClearProviderPayload clears the value of the "provider_payload" field.
func (u *PaymentOrderUpsertBulk) ClearProviderPayload() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProviderPayload()
	})
}

// SetDescription sets the "description" field.
func (u *PaymentOrderUpsertBulk) SetDescription(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateDescription() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PaymentOrderUpsertBulk) ClearDescription() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearDescription()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentOrderUpsertBulk) SetPaidAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdatePaidAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentOrderUpsertBulk) ClearPaidAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *PaymentOrderUpsertBulk) SetExpiresAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateExpiresAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *PaymentOrderUpsertBulk) ClearExpiresAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *PaymentOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
