// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
)

// ReferralCommissionCreate is the builder for creating a ReferralCommission entity.
type ReferralCommissionCreate struct {
	config
	mutation *ReferralCommissionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *ReferralCommissionCreate) SetUsageLogID(v int64) *ReferralCommissionCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetInviterUserID sets the "inviter_user_id" field.
func (_c *ReferralCommissionCreate) SetInviterUserID(v int64) *ReferralCommissionCreate {
	_c.mutation.SetInviterUserID(v)
	return _c
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (_c *ReferralCommissionCreate) SetInviteeUserID(v int64) *ReferralCommissionCreate {
	_c.mutation.SetInviteeUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ReferralCommissionCreate) SetAmount(v float64) *ReferralCommissionCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableAmount(v *float64) *ReferralCommissionCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReferralCommissionCreate) SetCreatedAt(v time.Time) *ReferralCommissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableCreatedAt(v *time.Time) *ReferralCommissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ReferralCommissionMutation object of the builder.
func (_c *ReferralCommissionCreate) Mutation() *ReferralCommissionMutation {
	return _c.mutation
}

// Save creates the ReferralCommission in the database.
func (_c *ReferralCommissionCreate) Save(ctx context.Context) (*ReferralCommission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReferralCommissionCreate) SaveX(ctx context.Context) *ReferralCommission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralCommissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralCommissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReferralCommissionCreate) defaults() {
	if _, ok := _c.mutation.Amount(); !ok {
		v := referralcommission.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := referralcommission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReferralCommissionCreate) check() error {
	if _, ok := _c.mutation.UsageLogID(); !ok {
		return &ValidationError{Name: "usage_log_id", err: errors.New(`ent: missing required field "ReferralCommission.usage_log_id"`)}
	}
	if _, ok := _c.mutation.InviterUserID(); !ok {
		return &ValidationError{Name: "inviter_user_id", err: errors.New(`ent: missing required field "ReferralCommission.inviter_user_id"`)}
	}
	if _, ok := _c.mutation.InviteeUserID(); !ok {
		return &ValidationError{Name: "invitee_user_id", err: errors.New(`ent: missing required field "ReferralCommission.invitee_user_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "ReferralCommission.amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReferralCommission.created_at"`)}
	}
	return nil
}

func (_c *ReferralCommissionCreate) sqlSave(ctx context.Context) (*ReferralCommission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReferralCommissionCreate) createSpec() (*ReferralCommission, *sqlgraph.CreateSpec) {
	var (
		_node = &ReferralCommission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(referralcommission.Table, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UsageLogID(); ok {
		_spec.SetField(referralcommission.FieldUsageLogID, field.TypeInt64, value)
		_node.UsageLogID = value
	}
	if value, ok := _c.mutation.InviterUserID(); ok {
		_spec.SetField(referralcommission.FieldInviterUserID, field.TypeInt64, value)
		_node.InviterUserID = value
	}
	if value, ok := _c.mutation.InviteeUserID(); ok {
		_spec.SetField(referralcommission.FieldInviteeUserID, field.TypeInt64, value)
		_node.InviteeUserID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(referralcommission.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(referralcommission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralCommission.Create().
//		SetUsageLogID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralCommissionUpsert) {
//			SetUsageLogID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralCommissionCreate) OnConflict(opts ...sql.ConflictOption) *ReferralCommissionUpsertOne {
	_c.conflict = opts
	return &ReferralCommissionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralCommissionCreate) OnConflictColumns(columns ...string) *ReferralCommissionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralCommissionUpsertOne{
		create: _c,
	}
}

type (
	// ReferralCommissionUpsertOne is the builder for "upsert"-ing
	//  one ReferralCommission node.
	ReferralCommissionUpsertOne struct {
		create *ReferralCommissionCreate
	}

	// ReferralCommissionUpsert is the "OnConflict" setter.
	ReferralCommissionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUsageLogID sets the "usage_log_id" field.
func (u *ReferralCommissionUpsert) SetUsageLogID(v int64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateUsageLogID() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldUsageLogID)
	return u
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *ReferralCommissionUpsert) AddUsageLogID(v int64) *ReferralCommissionUpsert {
	u.Add(referralcommission.FieldUsageLogID, v)
	return u
}

// SetInviterUserID sets the "inviter_user_id" field.
func (u *ReferralCommissionUpsert) SetInviterUserID(v int64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldInviterUserID, v)
	return u
}

// UpdateInviterUserID sets the "inviter_user_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateInviterUserID() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldInviterUserID)
	return u
}

// AddInviterUserID adds v to the "inviter_user_id" field.
func (u *ReferralCommissionUpsert) AddInviterUserID(v int64) *ReferralCommissionUpsert {
	u.Add(referralcommission.FieldInviterUserID, v)
	return u
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (u *ReferralCommissionUpsert) SetInviteeUserID(v int64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldInviteeUserID, v)
	return u
}

// UpdateInviteeUserID sets the "invitee_user_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateInviteeUserID() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldInviteeUserID)
	return u
}

// AddInviteeUserID adds v to the "invitee_user_id" field.
func (u *ReferralCommissionUpsert) AddInviteeUserID(v int64) *ReferralCommissionUpsert {
	u.Add(referralcommission.FieldInviteeUserID, v)
	return u
}

// SetAmount sets the "amount" field.
func (u *ReferralCommissionUpsert) SetAmount(v float64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateAmount() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *ReferralCommissionUpsert) AddAmount(v float64) *ReferralCommissionUpsert {
	u.Add(referralcommission.FieldAmount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralCommissionUpsertOne) UpdateNewValues() *ReferralCommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(referralcommission.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReferralCommissionUpsertOne) Ignore() *ReferralCommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralCommissionUpsertOne) DoNothing() *ReferralCommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralCommissionCreate.OnConflict
// documentation for more info.
func (u *ReferralCommissionUpsertOne) Update(set func(*ReferralCommissionUpsert)) *ReferralCommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralCommissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *ReferralCommissionUpsertOne) SetUsageLogID(v int64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *ReferralCommissionUpsertOne) AddUsageLogID(v int64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateUsageLogID() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateUsageLogID()
	})
}

// SetInviterUserID sets the "inviter_user_id" field.
func (u *ReferralCommissionUpsertOne) SetInviterUserID(v int64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetInviterUserID(v)
	})
}

// AddInviterUserID adds v to the "inviter_user_id" field.
func (u *ReferralCommissionUpsertOne) AddInviterUserID(v int64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddInviterUserID(v)
	})
}

// UpdateInviterUserID sets the "inviter_user_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateInviterUserID() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateInviterUserID()
	})
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (u *ReferralCommissionUpsertOne) SetInviteeUserID(v int64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetInviteeUserID(v)
	})
}

// AddInviteeUserID adds v to the "invitee_user_id" field.
func (u *ReferralCommissionUpsertOne) AddInviteeUserID(v int64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddInviteeUserID(v)
	})
}

// UpdateInviteeUserID sets the "invitee_user_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateInviteeUserID() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateInviteeUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *ReferralCommissionUpsertOne) SetAmount(v float64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ReferralCommissionUpsertOne) AddAmount(v float64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateAmount() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateAmount()
	})
}

// Exec executes the query.
func (u *ReferralCommissionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralCommissionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralCommissionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReferralCommissionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReferralCommissionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReferralCommissionCreateBulk is the builder for creating many ReferralCommission entities in bulk.
type ReferralCommissionCreateBulk struct {
	config
	err      error
	builders []*ReferralCommissionCreate
	conflict []sql.ConflictOption
}

// Save creates the ReferralCommission entities in the database.
func (_c *ReferralCommissionCreateBulk) Save(ctx context.Context) ([]*ReferralCommission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReferralCommission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReferralCommissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReferralCommissionCreateBulk) SaveX(ctx context.Context) []*ReferralCommission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralCommissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralCommissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralCommission.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralCommissionUpsert) {
//			SetUsageLogID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralCommissionCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReferralCommissionUpsertBulk {
	_c.conflict = opts
	return &ReferralCommissionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralCommissionCreateBulk) OnConflictColumns(columns ...string) *ReferralCommissionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralCommissionUpsertBulk{
		create: _c,
	}
}

// ReferralCommissionUpsertBulk is the builder for "upsert"-ing
// a bulk of ReferralCommission nodes.
type ReferralCommissionUpsertBulk struct {
	create *ReferralCommissionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralCommissionUpsertBulk) UpdateNewValues() *ReferralCommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(referralcommission.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReferralCommissionUpsertBulk) Ignore() *ReferralCommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralCommissionUpsertBulk) DoNothing() *ReferralCommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralCommissionCreateBulk.OnConflict
// documentation for more info.
func (u *ReferralCommissionUpsertBulk) Update(set func(*ReferralCommissionUpsert)) *ReferralCommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralCommissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *ReferralCommissionUpsertBulk) SetUsageLogID(v int64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *ReferralCommissionUpsertBulk) AddUsageLogID(v int64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateUsageLogID() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateUsageLogID()
	})
}

// SetInviterUserID sets the "inviter_user_id" field.
func (u *ReferralCommissionUpsertBulk) SetInviterUserID(v int64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetInviterUserID(v)
	})
}

// AddInviterUserID adds v to the "inviter_user_id" field.
func (u *ReferralCommissionUpsertBulk) AddInviterUserID(v int64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddInviterUserID(v)
	})
}

// UpdateInviterUserID sets the "inviter_user_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateInviterUserID() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateInviterUserID()
	})
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (u *ReferralCommissionUpsertBulk) SetInviteeUserID(v int64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetInviteeUserID(v)
	})
}

// AddInviteeUserID adds v to the "invitee_user_id" field.
func (u *ReferralCommissionUpsertBulk) AddInviteeUserID(v int64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddInviteeUserID(v)
	})
}

// UpdateInviteeUserID sets the "invitee_user_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateInviteeUserID() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateInviteeUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *ReferralCommissionUpsertBulk) SetAmount(v float64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ReferralCommissionUpsertBulk) AddAmount(v float64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateAmount() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateAmount()
	})
}

// Exec executes the query.
func (u *ReferralCommissionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReferralCommissionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralCommissionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralCommissionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
