// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
)

// ReferralCommissionUpdate is the builder for updating ReferralCommission entities.
type ReferralCommissionUpdate struct {
	config
	hooks    []Hook
	mutation *ReferralCommissionMutation
}

// Where appends a list predicates to the ReferralCommissionUpdate builder.
func (_u *ReferralCommissionUpdate) Where(ps ...predicate.ReferralCommission) *ReferralCommissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *ReferralCommissionUpdate) SetUsageLogID(v int64) *ReferralCommissionUpdate {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableUsageLogID(v *int64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *ReferralCommissionUpdate) AddUsageLogID(v int64) *ReferralCommissionUpdate {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// SetInviterUserID sets the "inviter_user_id" field.
func (_u *ReferralCommissionUpdate) SetInviterUserID(v int64) *ReferralCommissionUpdate {
	_u.mutation.ResetInviterUserID()
	_u.mutation.SetInviterUserID(v)
	return _u
}

// SetNillableInviterUserID sets the "inviter_user_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableInviterUserID(v *int64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetInviterUserID(*v)
	}
	return _u
}

// AddInviterUserID adds value to the "inviter_user_id" field.
func (_u *ReferralCommissionUpdate) AddInviterUserID(v int64) *ReferralCommissionUpdate {
	_u.mutation.AddInviterUserID(v)
	return _u
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (_u *ReferralCommissionUpdate) SetInviteeUserID(v int64) *ReferralCommissionUpdate {
	_u.mutation.ResetInviteeUserID()
	_u.mutation.SetInviteeUserID(v)
	return _u
}

// SetNillableInviteeUserID sets the "invitee_user_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableInviteeUserID(v *int64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetInviteeUserID(*v)
	}
	return _u
}

// AddInviteeUserID adds value to the "invitee_user_id" field.
func (_u *ReferralCommissionUpdate) AddInviteeUserID(v int64) *ReferralCommissionUpdate {
	_u.mutation.AddInviteeUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ReferralCommissionUpdate) SetAmount(v float64) *ReferralCommissionUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableAmount(v *float64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ReferralCommissionUpdate) AddAmount(v float64) *ReferralCommissionUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// Mutation returns the ReferralCommissionMutation object of the builder.
func (_u *ReferralCommissionUpdate) Mutation() *ReferralCommissionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReferralCommissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralCommissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReferralCommissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralCommissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ReferralCommissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(referralcommission.Table, referralcommission.Columns, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(referralcommission.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(referralcommission.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InviterUserID(); ok {
		_spec.SetField(referralcommission.FieldInviterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviterUserID(); ok {
		_spec.AddField(referralcommission.FieldInviterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InviteeUserID(); ok {
		_spec.SetField(referralcommission.FieldInviteeUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviteeUserID(); ok {
		_spec.AddField(referralcommission.FieldInviteeUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(referralcommission.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(referralcommission.FieldAmount, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralcommission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReferralCommissionUpdateOne is the builder for updating a single ReferralCommission entity.
type ReferralCommissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReferralCommissionMutation
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *ReferralCommissionUpdateOne) SetUsageLogID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableUsageLogID(v *int64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *ReferralCommissionUpdateOne) AddUsageLogID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// SetInviterUserID sets the "inviter_user_id" field.
func (_u *ReferralCommissionUpdateOne) SetInviterUserID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetInviterUserID()
	_u.mutation.SetInviterUserID(v)
	return _u
}

// SetNillableInviterUserID sets the "inviter_user_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableInviterUserID(v *int64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetInviterUserID(*v)
	}
	return _u
}

// AddInviterUserID adds value to the "inviter_user_id" field.
func (_u *ReferralCommissionUpdateOne) AddInviterUserID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.AddInviterUserID(v)
	return _u
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (_u *ReferralCommissionUpdateOne) SetInviteeUserID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetInviteeUserID()
	_u.mutation.SetInviteeUserID(v)
	return _u
}

// SetNillableInviteeUserID sets the "invitee_user_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableInviteeUserID(v *int64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetInviteeUserID(*v)
	}
	return _u
}

// AddInviteeUserID adds value to the "invitee_user_id" field.
func (_u *ReferralCommissionUpdateOne) AddInviteeUserID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.AddInviteeUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ReferralCommissionUpdateOne) SetAmount(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableAmount(v *float64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ReferralCommissionUpdateOne) AddAmount(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// Mutation returns the ReferralCommissionMutation object of the builder.
func (_u *ReferralCommissionUpdateOne) Mutation() *ReferralCommissionMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReferralCommissionUpdate builder.
func (_u *ReferralCommissionUpdateOne) Where(ps ...predicate.ReferralCommission) *ReferralCommissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReferralCommissionUpdateOne) Select(field string, fields ...string) *ReferralCommissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReferralCommission entity.
func (_u *ReferralCommissionUpdateOne) Save(ctx context.Context) (*ReferralCommission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralCommissionUpdateOne) SaveX(ctx context.Context) *ReferralCommission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReferralCommissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralCommissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ReferralCommissionUpdateOne) sqlSave(ctx context.Context) (_node *ReferralCommission, err error) {
	_spec := sqlgraph.NewUpdateSpec(referralcommission.Table, referralcommission.Columns, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReferralCommission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, referralcommission.FieldID)
		for _, f := range fields {
			if !referralcommission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != referralcommission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(referralcommission.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(referralcommission.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InviterUserID(); ok {
		_spec.SetField(referralcommission.FieldInviterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviterUserID(); ok {
		_spec.AddField(referralcommission.FieldInviterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InviteeUserID(); ok {
		_spec.SetField(referralcommission.FieldInviteeUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviteeUserID(); ok {
		_spec.AddField(referralcommission.FieldInviteeUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(referralcommission.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(referralcommission.FieldAmount, field.TypeFloat64, value)
	}
	_node = &ReferralCommission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralcommission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
