// Code generated by ent, DO NOT EDIT.

package referralcommission

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the referralcommission type in the database.
	Label = "referral_commission"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldInviterUserID holds the string denoting the inviter_user_id field in the database.
	FieldInviterUserID = "inviter_user_id"
	// FieldInviteeUserID holds the string denoting the invitee_user_id field in the database.
	FieldInviteeUserID = "invitee_user_id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the referralcommission in the database.
	Table = "referral_commissions"
)

// Columns holds all SQL columns for referralcommission fields.
var Columns = []string{
	FieldID,
	FieldUsageLogID,
	FieldInviterUserID,
	FieldInviteeUserID,
	FieldAmount,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ReferralCommission queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByInviterUserID orders the results by the inviter_user_id field.
func ByInviterUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviterUserID, opts...).ToFunc()
}

// ByInviteeUserID orders the results by the invitee_user_id field.
func ByInviteeUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteeUserID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
