// Code generated by ent, DO NOT EDIT.

package referralcommission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldID, id))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldUsageLogID, v))
}

// InviterUserID applies equality check predicate on the "inviter_user_id" field. It's identical to InviterUserIDEQ.
func InviterUserID(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldInviterUserID, v))
}

// InviteeUserID applies equality check predicate on the "invitee_user_id" field. It's identical to InviteeUserIDEQ.
func InviteeUserID(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldInviteeUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldAmount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCreatedAt, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldUsageLogID, v))
}

// InviterUserIDEQ applies the EQ predicate on the "inviter_user_id" field.
func InviterUserIDEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldInviterUserID, v))
}

// InviterUserIDNEQ applies the NEQ predicate on the "inviter_user_id" field.
func InviterUserIDNEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldInviterUserID, v))
}

// InviterUserIDIn applies the In predicate on the "inviter_user_id" field.
func InviterUserIDIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldInviterUserID, vs...))
}

// InviterUserIDNotIn applies the NotIn predicate on the "inviter_user_id" field.
func InviterUserIDNotIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldInviterUserID, vs...))
}

// InviterUserIDGT applies the GT predicate on the "inviter_user_id" field.
func InviterUserIDGT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldInviterUserID, v))
}

// InviterUserIDGTE applies the GTE predicate on the "inviter_user_id" field.
func InviterUserIDGTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldInviterUserID, v))
}

// InviterUserIDLT applies the LT predicate on the "inviter_user_id" field.
func InviterUserIDLT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldInviterUserID, v))
}

// InviterUserIDLTE applies the LTE predicate on the "inviter_user_id" field.
func InviterUserIDLTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldInviterUserID, v))
}

// InviteeUserIDEQ applies the EQ predicate on the "invitee_user_id" field.
func InviteeUserIDEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldInviteeUserID, v))
}

// InviteeUserIDNEQ applies the NEQ predicate on the "invitee_user_id" field.
func InviteeUserIDNEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldInviteeUserID, v))
}

// InviteeUserIDIn applies the In predicate on the "invitee_user_id" field.
func InviteeUserIDIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldInviteeUserID, vs...))
}

// InviteeUserIDNotIn applies the NotIn predicate on the "invitee_user_id" field.
func InviteeUserIDNotIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldInviteeUserID, vs...))
}

// InviteeUserIDGT applies the GT predicate on the "invitee_user_id" field.
func InviteeUserIDGT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldInviteeUserID, v))
}

// InviteeUserIDGTE applies the GTE predicate on the "invitee_user_id" field.
func InviteeUserIDGTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldInviteeUserID, v))
}

// InviteeUserIDLT applies the LT predicate on the "invitee_user_id" field.
func InviteeUserIDLT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldInviteeUserID, v))
}

// InviteeUserIDLTE applies the LTE predicate on the "invitee_user_id" field.
func InviteeUserIDLTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldInviteeUserID, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReferralCommission) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReferralCommission) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReferralCommission) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.NotPredicates(p))
}
