// Package ctxkey 定义用于 context.Value 的类型安全 key
package ctxkey

// Key 定义 context key 的类型，避免使用内置 string 类型（staticcheck SA1029）
type Key string

const (
	// ForcePlatform 强制平台（用于 /antigravity 路由），由 middleware.ForcePlatform 设置
	ForcePlatform Key = "ctx_force_platform"

	// ClientRequestID 客户端请求的唯一标识，用于追踪请求全生命周期（用于 Ops 监控与排障）。
	ClientRequestID Key = "ctx_client_request_id"
	// ClientRequestIDProvided indicates the request ID came from client-supplied headers (idempotency key),
	// not generated by the server middleware.
	ClientRequestIDProvided Key = "ctx_client_request_id_provided"

	// RetryCount 表示当前请求在网关层的重试次数（用于 Ops 记录与排障）。
	RetryCount Key = "ctx_retry_count"

	// IsClaudeCodeClient 标识当前请求是否来自 Claude Code 客户端
	IsClaudeCodeClient Key = "ctx_is_claude_code_client"
	// Group 认证后的分组信息，由 API Key 认证中间件设置
	Group Key = "ctx_group"

	// SingleAccountRetry 标识当前请求处于单账号 503 退避重试模式。
	// 在此模式下，Service 层可避免对 503 (MODEL_CAPACITY_EXHAUSTED) 设置长 cooldown。
	SingleAccountRetry Key = "ctx_single_account_retry"
)
